export const experts = [
  {
    id: 1,
    name: "Dr. Ayesha Khan",
    designation: "Clinical Psychologist",
    rating: 4.9,
    experience: 7,
    sessions: 1200,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "Specializes in anxiety, depression, and relationship counseling.",
  },
  {
    id: 2,
    name: "Mr. Rahul Mehta",
    designation: "Counseling Psychologist",
    rating: 4.7,
    experience: 5,
    sessions: 980,
    image: "https://randomuser.me/api/portraits/men/65.jpg",
    bio: "Expert in stress management and academic pressure.",
  },
  {
    id: 3,
    name: "Dr. Neha Singh",
    designation: "Child Psychologist",
    rating: 4.8,
    experience: 6,
    sessions: 1100,
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    bio: "Helps children and teens with emotional challenges.",
  },
  {
    id: 4,
    name: "Ms. Ankit Sharma",
    designation: "Mental Health Therapist",
    rating: 4.6,
    experience: 4,
    sessions: 870,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "Focuses on cognitive behavioral therapy and self-esteem.",
  },
  {
    id: 5,
    name: "Dr. Priya Verma",
    designation: "Psychiatrist",
    rating: 4.9,
    experience: 10,
    sessions: 1450,
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    bio: "Medical doctor with expertise in mood disorders.",
  },
  {
    id: 6,
    name: "Mr. Arjun Desai",
    designation: "Career Coach",
    rating: 4.5,
    experience: 3,
    sessions: 560,
    image: "https://randomuser.me/api/portraits/men/76.jpg",
    bio: "Guides young adults on career direction and motivation.",
  },
  {
    id: 7,
    name: "Ms. Sneha Kapoor",
    designation: "Behavioral Therapist",
    rating: 4.8,
    experience: 8,
    sessions: 1300,
    image: "https://randomuser.me/api/portraits/women/47.jpg",
    bio: "Works with clients struggling with behavioral issues and trauma.",
  },
  {
    id: 8,
    name: "Mr. Kabir Jain",
    designation: "Clinical Hypnotherapist",
    rating: 4.6,
    experience: 6,
    sessions: 940,
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    bio: "Specializes in hypnotherapy and inner child healing.",
  },
  {
    id: 9,
    name: "Dr. Riya Nair",
    designation: "LGBTQ+ Counselor",
    rating: 4.9,
    experience: 7,
    sessions: 1220,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    bio: "Supportive and affirming therapy for LGBTQ+ individuals.",
  },
  {
    id: 10,
    name: "Mr. Dev Raj",
    designation: "Addiction Specialist",
    rating: 4.4,
    experience: 5,
    sessions: 780,
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Helps overcome substance abuse and dependency issues.",
  },
  {
    id: 11,
    name: "Dr. Shalini Joshi",
    designation: "Marriage Counselor",
    rating: 4.8,
    experience: 9,
    sessions: 1280,
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    bio: "Expert in couple’s therapy and relationship dynamics.",
  },
  {
    id: 12,
    name: "Ms. Farhan Khan",
    designation: "Clinical Social Worker",
    rating: 4.7,
    experience: 6,
    sessions: 1020,
    image: "https://randomuser.me/api/portraits/men/81.jpg",
    bio: "Guides clients through life transitions and emotional health.",
  },
  {
    id: 13,
    name: "Dr. Lavanya Rao",
    designation: "Teen Counselor",
    rating: 4.9,
    experience: 8,
    sessions: 1160,
    image: "https://randomuser.me/api/portraits/women/41.jpg",
    bio: "Helps teenagers cope with identity and social pressures.",
  },
  {
    id: 14,
    name: "Mr. Vikram Dutta",
    designation: "Mental Wellness Coach",
    rating: 4.5,
    experience: 4,
    sessions: 620,
    image: "https://randomuser.me/api/portraits/men/55.jpg",
    bio: "Focuses on mindfulness, balance, and lifestyle therapy.",
  },
  {
    id: 15,
    name: "Ms. Shruti Rana",
    designation: "Mindfulness Practitioner",
    rating: 4.7,
    experience: 5,
    sessions: 790,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    bio: "Teaches mindfulness and meditation to manage stress.",
  },
  {
    id: 16,
    name: "Dr. Arvind Patel",
    designation: "Neuropsychologist",
    rating: 4.9,
    experience: 11,
    sessions: 1500,
    image: "https://randomuser.me/api/portraits/men/39.jpg",
    bio: "Deals with brain-behavior connections and trauma recovery.",
  },
  {
    id: 17,
    name: "Ms. Aditi Kulkarni",
    designation: "Grief Counselor",
    rating: 4.8,
    experience: 6,
    sessions: 880,
    image: "https://randomuser.me/api/portraits/women/62.jpg",
    bio: "Supports clients processing loss and emotional healing.",
  },
  {
    id: 18,
    name: "Mr. Samir Bansal",
    designation: "Depression & Anxiety Expert",
    rating: 4.6,
    experience: 7,
    sessions: 990,
    image: "https://randomuser.me/api/portraits/men/48.jpg",
    bio: "Helps individuals overcome chronic depression and anxiety.",
  },
  {
    id: 19,
    name: "Dr. Isha Chopra",
    designation: "Holistic Therapist",
    rating: 4.7,
    experience: 9,
    sessions: 1350,
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    bio: "Blends mental health practices with yoga and Ayurveda.",
  },
  {
    id: 20,
    name: "Mr. Rajeev Iyer",
    designation: "Self-Esteem Coach",
    rating: 4.5,
    experience: 5,
    sessions: 720,
    image: "https://randomuser.me/api/portraits/men/27.jpg",
    bio: "Empowers clients to build confidence and resilience.",
  },
  {
    id: 21,
    name: "Ms. Nitish Sharma",
    designation: "Mental Health Therapist",
    rating: 4.5,
    experience: 3,
    sessions: 890,
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    bio: "Focuses on cognitive behavioral therapy and self-esteem.",
  },
];
